CREATE TABLE [dbo].[TLAType]
(
[TLATypeID] [int] NOT NULL IDENTITY(1, 1),
[TLATypeName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IsDeleted] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TLAType] ADD CONSTRAINT [PK_TLA] PRIMARY KEY CLUSTERED ([TLATypeID]) ON [PRIMARY]
GO
