CREATE TABLE [dbo].[CN]
(
[CNID] [int] NOT NULL IDENTITY(1, 1),
[CN_XValue] [float] NOT NULL CONSTRAINT [DF_CN_CN_XValue] DEFAULT ((0)),
[CN_YValue] [float] NOT NULL CONSTRAINT [DF_CN_CN_YValue] DEFAULT ((0)),
[TLAID] [int] NULL,
[ATID] [int] NULL,
[CNTypeID] [int] NOT NULL,
[__ClassID] [int] NOT NULL,
[CanBeUsedLater] [bit] NULL CONSTRAINT [DF_CN_CanBeUsedLater] DEFAULT ((1)),
[IsDeleted] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CN] ADD CONSTRAINT [PK_CN_1] PRIMARY KEY CLUSTERED ([CNID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CN] ADD CONSTRAINT [FK_CN_AT] FOREIGN KEY ([ATID]) REFERENCES [dbo].[AT] ([ATID])
GO
ALTER TABLE [dbo].[CN] ADD CONSTRAINT [FK_CN_CNType] FOREIGN KEY ([CNTypeID]) REFERENCES [dbo].[CNType] ([CNTypeID])
GO
ALTER TABLE [dbo].[CN] ADD CONSTRAINT [FK_CN_TLA] FOREIGN KEY ([TLAID]) REFERENCES [dbo].[TLA] ([TLAID])
GO
