CREATE TABLE [dbo].[TLA_ILO]
(
[TLAID] [int] NOT NULL,
[ILOID] [int] NOT NULL,
[Percentages] [float] NOT NULL,
[IsDeleted] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TLA_ILO] ADD CONSTRAINT [PK_TLA_ILO] PRIMARY KEY CLUSTERED ([TLAID], [ILOID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TLA_ILO] ADD CONSTRAINT [FK_TLA_ILO_ILO] FOREIGN KEY ([ILOID]) REFERENCES [dbo].[ILO] ([ILOID])
GO
ALTER TABLE [dbo].[TLA_ILO] ADD CONSTRAINT [FK_TLA_ILO_TLA] FOREIGN KEY ([TLAID]) REFERENCES [dbo].[TLA] ([TLAID])
GO
